version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-cognito-mfa"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wcc1rlbjeh9t"
s3_prefix = "sam-cognito-mfa"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"dev\" ProjectName=\"sam-cognito-mfa\""
image_repositories = []
resolve_s3 = true
